kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: secondary-scheduler-role-binding
subjects:
- kind: ServiceAccount
  name: secondary-scheduler-operator
  namespace: openshift-secondary-scheduler-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secondary-scheduler-operator

