apiVersion: apps/v1
kind: Deployment
metadata:
  name: "secondary-scheduler"
  namespace: "openshift-secondary-scheduler-operator"
  labels:
    app: "secondary-scheduler"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "secondary-scheduler"
  template:
    metadata:
      labels:
        app: "secondary-scheduler"
    spec:
      serviceAccount: "secondary-scheduler"
      volumes:
        - name: "config-volume"
          configMap:
            name: "secondary-scheduler"
      containers:
        - name: "secondary-scheduler"
          image: ${IMAGE}
          imagePullPolicy: Always
          args:
            - /bin/kube-scheduler
            - --config=/etc/kubernetes/config.yaml
            - --v=6
          volumeMounts:
            - name: "config-volume"
              mountPath: "/etc/kubernetes"
